export const ORDERLIST = [
  {
    id: 1,
    name: "Christine Brooks",
    address: "089 Kutch Green Apt. 448",
    date: "04 Sep 2019",
    type: "Electric",
    status: "Completed",
  },
  {
    id: 2,
    name: "Rosie Pearson",
    address: "979 Immanuel Ferry Suite 526",
    date: "28 May 2019",
    type: "Book",
    status: "Processing",
  },
  {
    id: 3,
    name: "Darrell Caldwell",
    address: "8587 Frida Ports",
    date: "23 Nov 2019",
    type: "Medicine",
    status: "Rejected",
  },
  {
    id: 4,
    name: "Gilbert Johnston",
    address: "768 Destiny Lake Suite 600",
    date: "05 Feb 2019",
    type: "Mobile",
    status: "Completed",
  },
  {
    id: 5,
    name: "Alan Cain",
    address: "042 Mylene Throughway",
    date: "29 Jul 2019",
    type: "Watch",
    status: "Processing",
  },
  {
    id: 6,
    name: "Alfred Murray",
    address: "543 Weimann Mountain",
    date: "15 Aug 2019",
    type: "Medicine",
    status: "Completed",
  },
  {
    id: 7,
    name: "Maggie Sullivan",
    address: "New Scottieberg",
    date: "21 Dec 2019",
    type: "Watch",
    status: "Processing",
  },
  {
    id: 8,
    name: "Rosie Todd",
    address: "New Jon",
    date: "30 Apr 2019",
    type: "Medicine",
    status: "OnHold",
  },
  {
    id: 9,
    name: "Dollie Hines",
    address: "124 Lyla Forge Suite 975",
    date: "09 Jan 2019",
    type: "Book",
    status: "Transit",
  },
  {
    id: 10,
    name: "Kevin Wood",
    address: "456 Green Hill St.",
    date: "15 Mar 2020",
    type: "Laptop",
    status: "Completed",
  },
  {
    id: 11,
    name: "Samantha Blake",
    address: "789 Silver Creek Rd.",
    date: "22 Apr 2020",
    type: "Furniture",
    status: "Processing",
  },
  {
    id: 12,
    name: "Jason Carter",
    address: "321 Sunset Blvd",
    date: "17 Jun 2020",
    type: "Mobile",
    status: "Rejected",
  },
  {
    id: 13,
    name: "Emma Watson",
    address: "654 Riverdale Lane",
    date: "30 Jul 2020",
    type: "Book",
    status: "Completed",
  },
  {
    id: 14,
    name: "Oliver Queen",
    address: "987 Arrow St.",
    date: "12 Sep 2020",
    type: "Electric",
    status: "Transit",
  },
  {
    id: 15,
    name: "Sophia Clark",
    address: "852 Pine Avenue",
    date: "25 Oct 2020",
    type: "Watch",
    status: "OnHold",
  },
  {
    id: 16,
    name: "Michael Brown",
    address: "369 Oakwood Drive",
    date: "18 Nov 2020",
    type: "Medicine",
    status: "Completed",
  },
  {
    id: 17,
    name: "Ethan Foster",
    address: "753 Maple Lane",
    date: "07 Jan 2021",
    type: "Laptop",
    status: "Processing",
  },
  {
    id: 18,
    name: "Amelia Moore",
    address: "951 Broadway St.",
    date: "22 Feb 2021",
    type: "Furniture",
    status: "Rejected",
  },
  {
    id: 19,
    name: "Daniel Smith",
    address: "456 Walnut St.",
    date: "14 Mar 2021",
    type: "Book",
    status: "Completed",
  },
  {
    id: 20,
    name: "Grace Johnson",
    address: "147 Cedar Road",
    date: "29 May 2021",
    type: "Mobile",
    status: "Transit",
  },
  {
    id: 21,
    name: "Liam Davis",
    address: "753 Evergreen Ave",
    date: "10 Jun 2021",
    type: "Watch",
    status: "Processing",
  },
  {
    id: 22,
    name: "Ava White",
    address: "369 Birch Street",
    date: "17 Jul 2021",
    type: "Electric",
    status: "Completed",
  },
  {
    id: 23,
    name: "James Wilson",
    address: "852 Cherry Lane",
    date: "22 Aug 2021",
    type: "Medicine",
    status: "OnHold",
  },
  {
    id: 24,
    name: "Isabella Thomas",
    address: "654 Willow Blvd",
    date: "09 Sep 2021",
    type: "Laptop",
    status: "Rejected",
  },
  {
    id: 25,
    name: "Benjamin Martinez",
    address: "951 Redwood Ct.",
    date: "25 Oct 2021",
    type: "Furniture",
    status: "Completed",
  },
  {
    id: 26,
    name: "Charlotte Hernandez",
    address: "147 Cypress St.",
    date: "12 Dec 2021",
    type: "Book",
    status: "Transit",
  },
  {
    id: 27,
    name: "William Brown",
    address: "753 Magnolia Ave",
    date: "07 Jan 2022",
    type: "Mobile",
    status: "Processing",
  },
  {
    id: 28,
    name: "Mia Garcia",
    address: "852 Acacia Rd.",
    date: "19 Feb 2022",
    type: "Watch",
    status: "Completed",
  },
  {
    id: 29,
    name: "Alexander Anderson",
    address: "456 Palm Street",
    date: "30 Mar 2022",
    type: "Medicine",
    status: "Rejected",
  },
  {
    id: 30,
    name: "Evelyn Clark",
    address: "753 Chestnut Ave",
    date: "11 May 2022",
    type: "Laptop",
    status: "Completed",
  },
  {
    id: 31,
    name: "Lucas Lewis",
    address: "369 Maplewood St.",
    date: "24 Jun 2022",
    type: "Furniture",
    status: "Processing",
  },
  {
    id: 32,
    name: "Harper Hall",
    address: "147 Pineapple Ct.",
    date: "07 Aug 2022",
    type: "Book",
    status: "OnHold",
  },
  {
    id: 33,
    name: "Henry Allen",
    address: "852 Oak Avenue",
    date: "18 Sep 2022",
    type: "Electric",
    status: "Transit",
  },
  {
    id: 34,
    name: "Sofia Baker",
    address: "951 Linden Blvd",
    date: "29 Oct 2022",
    type: "Watch",
    status: "Completed",
  },
  {
    id: 35,
    name: "Mason Scott",
    address: "456 Fir Street",
    date: "11 Dec 2022",
    type: "Medicine",
    status: "Processing",
  },
  {
    id: 36,
    name: "Ella Rogers",
    address: "753 Cottonwood Ct.",
    date: "07 Jan 2023",
    type: "Laptop",
    status: "Rejected",
  },
  {
    id: 37,
    name: "Sebastian Phillips",
    address: "369 Laurel Rd.",
    date: "15 Mar 2023",
    type: "Furniture",
    status: "Completed",
  },
  {
    id: 38,
    name: "Victoria Campbell",
    address: "852 Elm St.",
    date: "27 Apr 2023",
    type: "Book",
    status: "Transit",
  },
  {
    id: 39,
    name: "Jack Nelson",
    address: "951 Willow Ave",
    date: "19 May 2023",
    type: "Mobile",
    status: "OnHold",
  },
  {
    id: 40,
    name: "Aria Mitchell",
    address: "147 Beechwood Blvd",
    date: "05 Jul 2023",
    type: "Electric",
    status: "Processing",
  },
];
