// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Login": {
    "title": "Login to Account",
    "descreption": "Please enter your email and password to continue",
    "email-address": "Email address:",
    "password": "Password:",
    "forget-password": "Forget Password?",
    "remember-password": "Remember Password",
    "button": "Sign In",
    "note": "Don’t have an account?",
    "redirect": "Create Account"
  },
  "Register": {
    "title": "Create an Account",
    "descreption": "Create a account to continue",
    "email-address": "Email address:",
    "password": "Password:",
    "user-name": "Username",
    "forget-password": "Forget Password?",
    "check-box": "I accept terms and conditions",
    "button": "Sign Up",
    "note": "Already have an account?",
    "redirect": "Login",
    "toast": "Success"
  },
  "Dashboard": {
    "title": "Dashboard",
    "sales-detail": "Sales Details",
    "deals-detail": "Deals Details",
    "revenua": "Revenua",
    "customers": "Customers",
    "featured": "Featured Products",
    "sales-analytics": "Sales Analytics",
    "user": "Total User",
    "order": "Total Order",
    "sales": "Total Sales",
    "pending": "Total Pending"
  },
  "Products": {
    "title": "Products",
    "edit": "Edit Product",
    "start": "Get starred",
    "prev": "Previous",
    "next": "Next"
  },
  "Favorites": {
    "title": "Favorites",
    "see-more": "See More",
    "edit": "Edit Product"
  },
  "Inbox": {
    "title": "Inbox",
    "email": "My Email",
    "inbox": "Inbox",
    "starred": "Starred",
    "sent": "Sent",
    "draft": "Draft",
    "spam": "Spam",
    "important": "Important",
    "bin": "Bin",
    "reset": "Reset",
    "label": "label",
    "compose": "Compose",
    "new messase": "New Message",
    "to": "To",
    "subject": "Subject",
    "send": "Send",
    "message": "Type something here"
  },
  "Order Lists": {
    "title": "Order Lists",
    "filter": "Filter By",
    "name": "name",
    "address": "address",
    "date": "date",
    "type": "type",
    "status": "status",
    "reset": "Reset Filter",
    "apply": "Apply Now",
    "not found": "No Order Found"
  },
  "Product Stock": {
    "title": "Product Stock",
    "search": "Search product name",
    "image": "Image",
    "name": "Product Name",
    "category": "Category",
    "price": "Price",
    "piece": "Piece",
    "color": "Available Color",
    "action": "Action"
  },
  "Pricing": {
    "title": "Pricing",
    "basic": "basic",
    "standard": "standard",
    "premium": "premium",
    "price": "montly charge",
    "setup": "free setup",
    "brandwidth": "Bandwidth Limit 10 GB",
    "user": "20 User Connection",
    "analytics": "Analytics Report",
    "access": "Public API Access",
    "intregation": "Plugins Intregation",
    "content": "Custom Content Management",
    "start": "Get starred",
    "note": "Start Your 30 Day Free Trial"
  },
  "Calender": {
    "title": "Calender",
    "more": "See More",
    "add": "Add New Event",
    "text": "You are going to :"
  },
  "To-do": {
    "title": "To-do",
    "button": "Add New Task"
  },
  "Contact": {
    "title": "Contact",
    "button": "Add New Contact",
    "more": "See More",
    "message": "message",
    "profile": "profile"
  },
  "AddNewContact": {
    "title": "Add New Contact"
  },
  "UpdateContact": {
    "title": "update contact",
    "update": "update now",
    "first name": "first name",
    "last name": "last name",
    "email": "your email",
    "phone": "phone number",
    "birth": "date of birth",
    "gender": "gender",
    "enter your first name": "enter your first name",
    "enter your last name": "enter your last name",
    "enter your email": "enter your email",
    "enter your phone number": "enter your phone number"
  },
  "Chatbox": {
    "title": "Message"
  },
  "Invoice": {
    "title": "Invoice",
    "from": "invoice from",
    "to": "invoice to",
    "date": "invoice date",
    "due": "due date",
    "send": "send",
    "total": "total"
  },
  "UI Elements": {
    "title": "UI Elements"
  },
  "Team": {
    "title": "Team",
    "more": "See More"
  },
  "Table": {
    "title": "Table"
  },
  "Global": {
    "settings": "Settings",
    "logout": "Logout",
    "page": "Page"
  },
  "ProductDetail": {
    "title": "Product Details",
    "description": "Description",
    "price": "Price",
    "color": "Color",
    "size": "Size",
    "quantity": "Quantity",
    "add": "Add to Cart",
    "buy": "Buy Now",
    "taxes": "inclusive of all taxes",
    "ship": "free shipping policy",
    "refund": "refund policy"
  },
  "Settings": {
    "title": "General Settings",
    "site name": "Site name",
    "copy right": "copy right",
    "seo title": "SEO title",
    "seo keywords": "SEO keywords",
    "seo description": "SEO decription",
    "save": "Save"
  },
  "Errors": {
    "to-required": "To is required",
    "mail-required": "Email is required",
    "mail-format": "Email is not valid",
    "password-required": "Password is required",
    "content-required": "Content is required",
    "subject-required": "Subject is required",
    "name-required": "Name is required",
    "address-required": "Address is required",
    "date-required": "Date is required",
    "type-required": "Type is required",  
    "status-required": "Status is required",
    "username-required": "Username is required"
  }
};
export default messages;