import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "../provider/jotai-providers";
import { QueryClientProviders } from "../provider/query-providers";
import { ToastContainer } from "react-toastify";
import { CacheProviders } from "../provider/cache-providers";
import { Suspense } from "react";
// import PageLoader from "./page-loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" data-toolpad-color-scheme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CacheProviders>
          <Suspense fallback = {<div>Loading...</div>}>
          <QueryClientProviders>
            <Providers>
              {/* <PageLoader/> */}
              {children}
              <ToastContainer />
            </Providers>
          </QueryClientProviders>
          </Suspense>
        </CacheProviders>
      </body>
    </html>
  );
}
