import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Nunito_Sans } from "next/font/google";
import "@/app/globals.css";
import { Providers } from "../../provider/jotai-providers";
import { QueryClientProviders } from "../../provider/query-providers";
import { ToastContainer } from "react-toastify";
import { CacheProviders } from "../../provider/cache-providers";
import { Suspense } from "react";
import ThemeProviders from "@/provider/theme-provider";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
// import PageLoader from "@/provider/page-loader";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-nunito-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} data-toolpad-color-scheme="light">
      <body className={`${nunitoSans.variable} antialiased`}>
        {/* <PageLoader> */}
          <NextIntlClientProvider>
            <CacheProviders>
              <Suspense fallback={<div>Loading...</div>}>
                <QueryClientProviders>
                  <Providers>
                    <ThemeProviders>{children}</ThemeProviders>
                    <ToastContainer />
                  </Providers>
                </QueryClientProviders>
              </Suspense>
            </CacheProviders>
          </NextIntlClientProvider>
        {/* </PageLoader> */}
      </body>
    </html>
  );
}
